# Compiles ui document into python classes.
pyuic6 -x -o ./AutoGenerated/MainWindow.py ./UIDesignerFiles/mainWindow.ui

pyuic6 -x -o ./AutoGenerated/SettingsWidget.py ./UIDesignerFiles/settingsWidget.ui