from AutoGenerated.MainWindow import *
import UI.MainWindowExtension

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.onResize = None
    def resizeEvent(self, event):
        QtWidgets.QMainWindow.resizeEvent(self, event)
        if self.onResize is not None:
            self.onResize()

    def setOnResize(self, func):
        self.onResize = func


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MainWindow()
    ui = UI.MainWindowExtension.MainWindowExtension(MainWindow)
    MainWindow.setOnResize(ui.imageAnnotator.resizeImage)
    MainWindow.show()
    sys.exit(app.exec())

