from AutoGenerated.MainWindow import *
import UI.MainWindowExtension

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI.MainWindowExtension.MainWindowExtension()
    ui.setupUi(MainWindow)
    ui.connectInputs()
    MainWindow.show()
    sys.exit(app.exec())

