# The purpose of this extension is to extend the functionality of the MainWindow class (hence the name).
# These extensions will handle receiving user input and connecting to the correct methods.

# Will normally avoid importing *, but we need access to everything within the MainWindowClass.
from AutoGenerated.MainWindow import *
from PyQt6.QtWidgets import QFileDialog

class MainWindowExtension(Ui_MainWindow):
    def connectInputs(self):
        self.browseOutputPath.clicked.connect(self.browseForOutputPath)

    def browseForOutputPath(self):
        fname = QFileDialog.getExistingDirectory(None, 'Select Output Folder', '../')
        self.outputPath.setText(fname)

