# The purpose of this extension is to extend the functionality of the MainWindow class (hence the name).
# These extensions will handle receiving user input and connecting to the correct methods.

# Will normally avoid importing *, but we need access to everything within the MainWindowClass.
from AutoGenerated.MainWindow import *
from UI.SettingsWidgetExtension import *
from SupportClasses.OutputHandler import OutputHandler
from SupportClasses.ModelHandler import ModelHandler


class MainWindowExtension(Ui_MainWindow):
    def __init__(self, MainWindow):
        self.outputHandler = OutputHandler()
        self.modelHandler = ModelHandler()
        self.settingsWidget = None
        self.settingsWindow = None
        self.setupUi(MainWindow)
        self.connectInputs()

    def createNew(self):
        self.settingsWidget.show()

    def connectInputs(self):
        self.actionSetup.triggered.connect(self.createNew)
        self.settingsWidget = QtWidgets.QWidget()
        self.settingsWindow = SettingsWidgetExtension(self.outputHandler, self.modelHandler, self.settingsWidget)
        self.settingsWindow.outputHandler.settingsWidgetExtension = self.settingsWindow
        self.actionLoad_Existing.triggered.connect(self.loadExistingProject)

    def loadExistingProject(self):
        self.settingsWindow.browseForOutputPath()
        if self.settingsWindow.setupOutputFolder():
            print("Loaded existing project at " + self.settingsWindow.outputHandler.root)


    def goToNextImage(self):
        pass

    def goToPreviousImage(self):
        pass

    def setDeleteMode(self):
        pass

    def setEditMode(self):
        pass

    def setAnnotateMode(self):
        pass


