
from AutoGenerated.SettingsWidget import *
from PyQt6.QtWidgets import QFileDialog
from SupportClasses.VideoDicer import VideoDicer


class SettingsWidgetExtension(Ui_SettingsWidget):
    def __init__(self, outputHandler, modelHandler, parent):
        self.videoDicer = VideoDicer()
        self.outputHandler = outputHandler
        self.modelHandler = modelHandler
        self.setupUi(parent)
        self.connectInputs()

    def connectInputs(self):
        self.browseOutputPath.clicked.connect(self.browseForOutputPath)
        self.browseModelPath.clicked.connect(self.browseForDetectionModelPath)
        self.importImageFolder.clicked.connect(self.browseForFolderOfImages)
        self.importVideo.clicked.connect(self.browseForVideo)
        self.importExisting.clicked.connect(self.browseForExistingAnnotatedSet)
        self.confirmSettings.clicked.connect(self.onConfirmSettings)

    def onConfirmSettings(self):
        self.setupOutputFolder()

    def setupOutputFolder(self) -> bool:
        success = True
        if self.outputHandler.setOutputFolderPath(self.outputPath.text()):
            self.outputHandler.setUpFolder()
        else:
            success = False

        return success


    def browseForOutputPath(self):
        fname = QFileDialog.getExistingDirectory(None, 'Select your outpur folder', '../')
        self.outputPath.setText(fname)

    def browseForDetectionModelPath(self):
        fname = QFileDialog.getOpenFileName(None, 'Select your object detection model', '../')
        self.modelPath.setText(fname[0])

    def browseForFolderOfImages(self):
        fname = QFileDialog.getExistingDirectory(None, 'Select folder of images to import', '../')
        if self.setupOutputFolder():
            self.outputHandler.importImageFolder(fname)

    def browseForVideo(self):
        fname = QFileDialog.getOpenFileName(None, 'Select video to import', '../')
        if self.setupOutputFolder():
            pass

    def browseForExistingAnnotatedSet(self):
        fname = QFileDialog.getExistingDirectory(None, 'Select existing annotation set', '../')
        if self.setupOutputFolder():
            pass

    def updateImageCounts(self, counts):
        # format is [tot, labeled, unlabeled]
        self.totImages.setText(str(counts[0]))
        self.labeledImages.setText(str(counts[1]))
        self.unlabeled.setText(str(counts[2]))